### PR TITLE
fixing: Could not resolve dependency Cypress 10

### PR DESCRIPTION
**Pull request by medamineamara**
we get these error after upgrading to cypress 10 
so I added version in the list
Will fix this issue #31

### CODE REVIEW

**Comment by alex-w0** [comment]
@babangsund Can you approve the merge request?

**Review by babangsund — APPROVED** [review]

**Comment by alex-w0** [comment]
@babangsund Thanks for the merge. Can you also release a new version and publish it to npm? That would be great!

**Comment by babangsund** [comment]
1.9 should already be published this morning :)

**Comment by alex-w0** [comment]
@babangsund Thanks, I noticed that too, a few minutes later. Github shows that version v1.9 was released on November 29, 2021, which made me think that no newer version was released :)

**Pull request merged**
