### PR TITLE
Add type property to package.json

### PR DESCRIPTION
**Pull request by prewk**
As per @nerumo's suggestion in #12.

Thanks for a great package!

### CODE REVIEW

**Comment by babangsund** [comment]
Thanks!

**Comment by prewk** [comment]
Could you perhaps do a patch-version bump for the npm package? Otherwise it won't reach us users :)

**Comment by babangsund** [comment]
I'll make a release today :-)

**Comment by prewk** [comment]
You may have forgotten to release :) (Still on `1.6.0`)

**Comment by babangsund** [comment]
Just published `1.7.0` :-)

**Pull request merged**
